import Contact from "@/components/cta/Contact";
import Footer from "@/components/footer/Footer";
import Header from "@/components/hero/Header";
import TopText from "@/components/hero/TopText";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <>
      <TopText />
      <Header />
      <main>{children}</main>
      <Contact className="relative -mb-20" />
      <Footer />
    </>
  );
}
