import localFont from "next/font/local";
import { getLocale } from "next-intl/server";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { CartProvider } from "@/context/CartContext";
import AuthProvider from "@/lib/auth/AuthProvider";
import { WishlistProvider } from "@/context/WishlistContext";
import { Toaster } from "react-hot-toast";

const satoshi = localFont({
  src: "../../fonts/Satoshi/Satoshi.ttf",
  variable: "--font-satoshi",
});

const IntegralCF = localFont({
  src: [
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-bold.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-boldoblique.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-demibold.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-demiboldoblique.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-extrabold.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-extraboldoblique.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-heavy.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-heavyoblique.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-medium.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-mediumoblique.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-regular.otf",
    },
    {
      path: "../../fonts/Integral-CF/Fontspring-DEMO-integralcf-regularoblique.otf",
    },
  ],
  variable: "--font-integral-cF",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const lang = await getLocale();
  return (
    <html lang={lang} className="scroll-smooth">
      <body className={`${satoshi.variable} ${IntegralCF.variable}`}>
        <AuthProvider>
          <NextIntlClientProvider>
            <CartProvider>
              <WishlistProvider>
                {children}
                <Toaster position="top-center" />
              </WishlistProvider>
            </CartProvider>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
